### ISSUE TITLE
Any text disappears when it's between </> arrows

### ISSUE THREAD

**Issue by 13steinj** [laurencedawson/reddit-sync-development#1174]
Any and all text between a < and a > doesn't display. Sony Xperia Z, android 4.3. It's been a bit of an annoyance since day one however I kept forgetting to report it.

My apologies if there's already an open issue on this, github's search found nothing for me and I didn't want to flip through 13 pages on mobile.

**Comment by daboross** [comment]
Experiencing this on an Oppo Find 7 with Nameless ROM too, if that's at all relevant. This is really the only reason I'm not using reddit sync 100% of the time :/.

**Comment by 13steinj** [comment]
This also occurs with some other characters in specific situations, such as $ in code blocks. I'm not sure if a custom markdown parser is used; or if there is an issue with the html reader currently used (and that's just barfing on chars); but it may be better to switch to the opposite.

**Comment by OvermindDL1** [comment]
Ditto, always a constant issue.

**Comment by laurencedawson** [comment]
Fixed for the next release. Cheers.

**Comment by 13steinj** [comment]
Wonderful!

**Comment by OvermindDL1** [comment]
Unsure if it is released yet, but I just updated today and it is still not fixed as can be seen by opening https://www.reddit.com/r/cpp_questions/comments/4u8q8h/_/ in the app vs the browser.

**Comment by machinator2** [comment]
You must still be on 11.5.10. That is currently the most recent version of the app (beta), but it is not the version of the app incorporating this fix. Ljdawson has yet to release it.

**Comment by 13steinj** [comment]
@laurencedawson This is not fixed.
![screenshot_2016-08-22-12-34-01](https://cloud.githubusercontent.com/assets/10525230/17862814/e39cac3c-6864-11e6-9b0f-e6f267c2e87e.png) and 
![screenshot_2016-08-22-12-33-53](https://cloud.githubusercontent.com/assets/10525230/17862827/f62f6394-6864-11e6-9bba-2aa89305fa45.png)

show this. The only difference between when this issue is created and after it was closed is that the first word shows up, while anything after it does not. This happened on the version before 11.6.6, and remains after having updated to 11.6.6
